version: "3"

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - sporto-registras-mariadb:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '33061:3306'
    networks:
      - internal

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - 9930:9000
      - 9931:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESSKEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRETKEY}
    command: server --console-address ":9001" /data
    networks:
      - internal

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 30;
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ACCESSKEY} ${MINIO_SECRETKEY};
      /usr/bin/mc mb myminio/${MINIO_BUCKET};
      /usr/bin/mc policy set public myminio/${MINIO_BUCKET};
      exit 0;
      "
    networks:
      - internal

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - mariadb
    networks:
      - internal

  wordpress:
    depends_on:
      - mariadb
      - minio
    build:
      context: .
    links:
      - mariadb
    volumes:
      - ./html/app/themes/sporto-registras:/opt/wordpress/html/app/themes/sporto-registras:rw
    env_file: 
      - ./.env
    ports:
      - 80:80
    restart: always
    networks:
      - internal

networks:
  internal:

volumes:
  sporto-registras-mariadb:
    driver: local